version: '3'
services:
  react-app:
    depends_on:
      - backend
    image: node:18-alpine
    restart: always
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 5000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    container_name: react-app
  backend:
    depends_on:
      - mysql
    restart: always
    image: node:18-alpine
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: deneme
      MYSQL_PORT: 3308
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 5000:5000
    container_name: backend
  mysql:
    image: mysql
    ports:
      - 3308:3308
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: deneme
    container_name: mysql

volumes:
  mysql-data:
    driver: local
  init:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './'
